#server.port=8080

server:
  port: 8080
  
  
# spring.datasource.url=jdbc:mysql://localhost:3306/whf3
  
# spring.datasource.username=root
  
# spring.jpa.hibernate.ddl-auto=update
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/whf3
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update  